### ISSUE TITLE
Images need to be square

### ISSUE THREAD

**Issue by lloydwatkin** [xmppjs/logo#1]
Just uploaded https://github-camo.global.ssl.fastly.net/ba0608a7816029baedc344642f554161585cc78d/687474703a2f2f6e6f64652d786d70702e6769746875622e696f2f6c6f676f2f7374656e63696c2e737667 to gravatar and its cropped the top and bottom as image is not square.

See `node-xmpp` logo for example.

**Comment by dodo** [comment]
Oh, yeah right. i forgot about those two. (and fixed with da7109b29b)

thanks for the `index.html` btw :}

**Comment by lloydwatkin** [comment]
updated gravatar, thanks for the great work!
